import os

# Resolve Digests directory relative to the project root directory
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIGESTS_DIR = os.path.join(PROJECT_ROOT, "digests")


def save_digest(
    analysis_text: str,
    run_date: str,
    num_videos: int = 0,
    num_channels: int = 0,
) -> str:
    """
    Saves the analysis markdown to digests/{run_date}.md with an header.
    Returns the absolute filepath.
    """
    os.makedirs(DIGESTS_DIR, exist_ok=True)

    header = f"""# Trend Digest — {run_date}
_Generated by trend-sensor. {num_videos} videos analysed from {num_channels} channels._

---
"""

    full_content = header + "\n" + analysis_text
    file_name = f"{run_date}.md"
    file_path = os.path.join(DIGESTS_DIR, file_name)

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(full_content)

    return file_path


def print_summary(analysis_text: str) -> None:
    """
    Prints the first 1000 characters of the analysis to stdout.
    """
    print("\n--- DIGEST SUMMARY (First 1000 Characters) ---")
    if len(analysis_text) <= 1000:
        print(analysis_text)
    else:
        print(analysis_text[:1000] + "\n... [TRUNCATED] ...")
    print("---------------------------------------------\n")
