channels:
  - id: UCOzMAa6IhV6uwYQATYG_2kg  # Novara Media
    name: "Novara Media"
    tier: core

  - id: UC-3jIAlnQmbbVMV6gR7K8aQ  # The Majority Report w/ Sam Seder
    name: "The Majority Report"
    tier: core

  - id: UCJm2TgUqtK1_NLBrjNQ1P-w  # Second Thought
    name: "Second Thought"
    tier: core

  - id: UC-AQKm7HUNMmxjdS371MSwg  # Channel 5 with Andrew Callaghan
    name: "Channel 5 with Andrew Callaghan"
    tier: core

  - id: UCzuqE7-t13O4NIDYJfakrhw  # Democracy Now!
    name: "Democracy Now!"
    tier: core

  - id: UCJmlCcnfMlyPA2oSbb072QA  # Hakim
    name: "Hakim"
    tier: core

  - id: UCSmOl7Hau-YX2VKfz1CMAZQ  # Current Affairs
    name: "Current Affairs"
    tier: broad